"""empty message

Revision ID: 122acf4ca311
Revises: 213264aded57
Create Date: 2016-03-29 00:42:33.838185

"""

# revision identifiers, used by Alembic.
revision = '122acf4ca311'
down_revision = '213264aded57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'image')
    op.add_column('wishes', sa.Column('url', sa.String(length=255), nullable=True))
    op.drop_column('wishes', 'image')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('wishes', 'url')
    op.add_column('persons', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
