"""empty message

Revision ID: 363c95029955
Revises: 23fcb15128ce
Create Date: 2016-03-20 17:25:18.532847

"""

# revision identifiers, used by Alembic.
revision = '363c95029955'
down_revision = '23fcb15128ce'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('addon', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wish')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('addon', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userid'], [u'persons.id'], name=u'wish_userid_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'wish_pkey')
    )
    op.drop_table('wishes')
    ### end Alembic commands ###
